nodeLinker: node-modules
enableGlobalCache: true
logFilters:
  - code: YN0002 # MISSING_PEER_DEPENDENCY
    level: discard
  - code: YN0060 # INCOMPATIBLE_PEER_DEPENDENCY
    level: discard
  - code: YN0076 # INCOMPATIBLE_ARCHITECTURE
    level: discard
